file = open('codingal.txt')
print(file.read())
file.close()
file = open('codingal.txt', 'w')
file.write("My name is Bhavishya and I'm 14 years old")
file.close()
file = open('codingal.txt')
print(file.read())
file.close()
file = open('codingal.txt', 'a')
file.write(" My name is Bhavishya and I'm 14 years old")
file.close()
file = open('codingal.txt')
print(file.read())
file.close()