input1 = input("Enter the name of your first file with the extension:")
input2 = input("Enter the name of your second file with the extension:")
file1 = open(input1)
file2 = open(input2)
print("The first file is: \n")
print(file1.read(), "\n")
print("The second file is: \n")
print(file2.read(), "\n")
file1.close()
file2.close()
file1 = open(input1, "a")
file2 = open(input2)
file1.write("\n")
file1.write(file2.read())
file1.seek(0)
file2.seek(0)
file1.close()
file1 = open(input1)
print(file1.read())
file1.close()
file2.close()